name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'horcrux-api/src/**'
      - '.forgejo/workflows/docs.yml'

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-docs-

      - name: Build rustdoc
        run: cargo doc --no-deps --all-features --workspace

      - name: Prepare docs
        run: |
          mkdir -p public
          cp -r target/doc/* public/
          cp -r docs/* public/ 2>/dev/null || true
          echo '<meta http-equiv="refresh" content="0; url=horcrux_api/index.html">' > public/index.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: forgejo-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
