name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl tools
        if: contains(matrix.target, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-${{ matrix.target }}-

      - name: Build CLI
        run: cargo build --release --target ${{ matrix.target }} -p horcrux-cli

      - name: Build API server
        run: cargo build --release --target ${{ matrix.target }} -p horcrux-api --all-features

      - name: Create archive
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/horcrux dist/
          cp target/${{ matrix.target }}/release/horcrux-api dist/
          cp README.md LICENSE dist/ 2>/dev/null || true
          cp -r docs dist/ 2>/dev/null || true
          cp config.example.toml dist/ 2>/dev/null || true
          cd dist
          tar -czvf ../horcrux-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }} *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: horcrux-${{ matrix.target }}
          path: horcrux-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }}

  build-ui-release:
    name: Build Web UI Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install trunk
        run: cargo install trunk

      - name: Build UI
        working-directory: horcrux-ui
        run: trunk build --release

      - name: Create archive
        run: |
          cd horcrux-ui/dist
          tar -czvf ../../horcrux-ui-${{ github.ref_name }}.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: horcrux-ui
          path: horcrux-ui-${{ github.ref_name }}.tar.gz

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-release, build-ui-release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate changelog
        id: changelog
        run: |
          echo "## Changes" > CHANGELOG.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG.md 2>/dev/null || echo "- Initial release" >> CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            artifacts/**/*.tar.gz
          draft: false
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
